---
abstract: "Encode or decode each element of a reference and it's sub-references."
author:
  - 'Sebastian willing <sewi@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Encode-Deep
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Encode: 0
  Exporter: 0
version: 0.01
